### ISSUE TITLE
PDF is not working

### ISSUE THREAD

**Issue by poke64738** [jaredmorgs/USB_BT_Joystick_Center#1]
Your created PDF:

https://github.com/jaredmorgs/USB_BT_Joystick_Center/raw/master/tmp/en-US/pdf/USB_BT_Joystick_Center-6-USB_BT_Joystick_Center-en-US.pdf

... is not working.

**Comment by jaredmorgs** [comment]
GitHub have seemed to have changed the link from:

https://github.com/jaredmorgs/USB_BT_Joystick_Center/raw/master/tmp/en-US/pdf/USB_BT_Joystick_Center-6-USB_BT_Joystick_Center-en-US.pdf

to:

https://github.com/jaredmorgs/USB_BT_Joystick_Center/blob/master/tmp/en-US/pdf/USB_BT_Joystick_Center-6-USB_BT_Joystick_Center-en-US.pdf?raw=true

I can access the guide from the raw=true link.

Update the link in your Play Store description and you'll be fine.

Jared Morgan
M: +61413005479
Connect with me through:
twitter.com/!#/jaredmorgs
jaredleonmorgan.blogspot.com
facebook.com/jaredmorgs

**Comment by poke64738** [comment]
Accessing is not the problem… the PDF is damaged, since 2 month.

greetings
poke

Am 15.01.2013 um 03:12 schrieb Jared Morgan notifications@github.com:

> GitHub have seemed to have changed the link from: 
> 
> https://github.com/jaredmorgs/USB_BT_Joystick_Center/raw/master/tmp/en-US/pdf/USB_BT_Joystick_Center-6-USB_BT_Joystick_Center-en-US.pdf 
> 
> to: 
> 
> https://github.com/jaredmorgs/USB_BT_Joystick_Center/blob/master/tmp/en-US/pdf/USB_BT_Joystick_Center-6-USB_BT_Joystick_Center-en-US.pdf?raw=true 
> 
> I can access the guide from the raw=true link. 
> 
> Update the link in your Play Store description and you'll be fine. 
> 
> Jared Morgan 
> M: +61413005479 
> Connect with me through: 
> twitter.com/!#/jaredmorgs 
> jaredleonmorgan.blogspot.com 
> facebook.com/jaredmorgs 
>

**Comment by jaredmorgs** [comment]
Sorry, but you're going to need to be more specific.

I just downloaded the manual then, and opened it on my Fedora 17 machine
using evince PDF viewer. When I download the file and open it on my PC,
everything looks perfect to me, just as it did when I finalized it and
released it to you.

What are you seeing? What PDF viewer are you using? Can you attach the copy
of the manual you get when you download it, and send it to me through email?

Jared Morgan
M: +61413005479
Connect with me through:
twitter.com/!#/jaredmorgs
jaredleonmorgan.blogspot.com
facebook.com/jaredmorgs

**Comment by poke64738** [comment]
I'm using a Mac (with Snow Leopard + Mountain Lion)… and the System PDF Viewer is telling me: "Can not open PDF file. Maybe this PDF is damaged."

I had no problems with the early versions, but since 2 month the pdf file is damaged.

greetings
poke

Am 15.01.2013 um 04:31 schrieb Jared Morgan notifications@github.com:

> Sorry, but you're going to need to be more specific. 
> 
> I just downloaded the manual then, and opened it on my Fedora 17 machine 
> using evince PDF viewer. When I download the file and open it on my PC, 
> everything looks perfect to me, just as it did when I finalized it and 
> released it to you. 
> 
> What are you seeing? What PDF viewer are you using? Can you attach the copy 
> of the manual you get when you download it, and send it to me through email? 
> 
> Jared Morgan 
> M: +61413005479 
> Connect with me through: 
> twitter.com/!#/jaredmorgs 
> jaredleonmorgan.blogspot.com 
> facebook.com/jaredmorgs 
>

**Comment by jaredmorgs** [comment]
Hi Poke

The problem is not at your end.

I work with some guys who use Mac as well, and got them to do some
troubleshooting.

The PDF does not open for them either using System Preview. The same
message as the one you report displays.

pdfpen opens the file, but it is pretty bad.

The desktop Kindle app opens the file correctly.

Safari, GoodReader and iBooks also have issues with the file.

My colleague then built the same book on an alternative Linux OS, and the
same issues occurred with his build.

This leads me to believe that the issue is with Publican (what I used to
generate the PDF), and I am raising a bug report as soon as I finish typing
this. I am not sure when this issue will be resolved.

HTML output will be unaffected by this issue. Is there a way I can deliver
a html version of the guide to you for hosting on a website while the issue
is fixed?

**Comment by jaredmorgs** [comment]
I have used GitHub to host the guide at jaredmorgs.github.com which will work-around the pdf issue until such time as it is solved upstream.
